name: Run Screener

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo "Workflow loaded successfully"
